name: Update the fixture files audited by the PageSpeed Insight API
on: [push, pull_request]

jobs:
  update-fixture-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: dom, iconv, json, libxml, zip
          tools: composer

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Configure Composer cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install

      - name: Configure git user
        run: |
          git config --global user.email "alain.schlesser@gmail.com"
          git config --global user.name "Alain Schlesser"

      - name: Check if remote branch exists
        id: remote-branch
        run: echo ::set-output name=exists::$([[ -z $(git ls-remote --heads origin update-fixture-files) ]] && echo "0" || echo "1")

      - name: Create branch to base pull request on
        if: steps.remote-branch.outputs.exists == 0
        run: |
          git checkout -b update-fixture-files

      - name: Fetch existing branch to add commits to
        if: steps.remote-branch.outputs.exists == 1
        run: |
          git fetch --all --prune
          git checkout update-fixture-files
          git pull --no-rebase

      - name: Download ngrok
        run: |
          curl https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.tgz --output ngrok-stable-linux-amd64.tgz
          tar xvzf ngrok-stable-linux-amd64.tgz
          mv ngrok /usr/local/bin

      - name: Download wp-cli
        run: |
          curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          chmod +x wp-cli.phar
          mv wp-cli.phar /usr/local/bin/wp
          wp --info
